image: ghcr.io/traversaro/gitpod-ubuntu-20.04:latest
ports:
- port: 6080
  onOpen: notify
- port: 10000-20000
  onOpen: ignore
workspaceLocation: "."
tasks:
- command: start-vnc-session.sh
- command: gp await-port 6080 && gp preview $(gp url 6080)
- init: sudo apt-get update && sudo apt-get upgrade -y
  command: sudo apt-get install -y git libffi-dev libssl-dev
           sudo apt-get install -y wget
           sudo apt-get install -y flex
           sudo apt-get install -y bison
           sudo apt-get install -y gperf
           sudo apt-get install -y python3
           sudo apt-get install -y python3-pip
           sudo apt-get install -y python3-setuptools